---
- name: stop controlcenter
  shell: docker-compose down
  args:
    chdir: /opt/stereum/controlcenter
  # ignore errors in case the container is not running
  ignore_errors: yes

- name: delete previous release
  file:
    path: /opt/stereum/controlcenter/stereum
    state: absent   
  ignore_errors: yes 

- name: Install git
  apt:
    update_cache: yes
    name:
    - git    
    state: latest

- name: prepare installer directory
  file:
    path: /opt/stereum/controlcenter
    state: directory
    owner: stereum
    mode: '0755'

- name: checkout stereum-install
  shell: "git clone https://github.com/stereum-dev/ethereum2-ansible.git stereum"
  args:
    chdir: /opt/stereum/controlcenter

- name: checkout stereum-install release tag
  shell: "git checkout tags/{{ stereum_version }}"
  args:
    chdir: /opt/stereum/controlcenter/stereum

- name: create .env
  shell: "echo \"stereum_version_tag\"={{ stereum_version }} > .env"
  args:
    chdir: /opt/stereum/controlcenter/

- name: create playbook.yaml
  shell: "cp init-setup.yaml playbook.yaml"
  args:
    chdir: /opt/stereum/controlcenter/stereum

- name: write inventory
  template:
    src: inventory.yaml
    dest: /opt/stereum/controlcenter/stereum/inventory.yaml
    owner: stereum
    mode: '0644'

- name: write docker-compose
  template:
    src: docker-compose.yaml
    dest: /opt/stereum/controlcenter/docker-compose.yaml
    owner: stereum
    mode: '0644'

- name: start controlcenter
  shell: docker-compose up -d
  args:
    chdir: /opt/stereum/controlcenter
