---
- name: Docker on CentOS
  include_tasks: docker-centos.yaml
  when: ansible_distribution == "CentOS"

- name: Docker on Ubuntu
  include_tasks: docker-ubuntu.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: enable service docker
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: add stereum user to docker group
  user:
    name: "{{ ubuntu_common_stereum_user_name }}"
    groups: docker
    append: yes

# EOF