version: "3"
services:
  controlcenter:
    image: "stereum/control-center-web:{{ controlcenter_version }}"
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - /home/stereum/.ssh:/root/.ssh
      - $PWD/inventory.yaml:/opt/app/inventory.yaml
      - $PWD/stereum:/opt/app/stereum-release