version: "3"
services:
  controlcenter:
    image: "stereum/control-center-web:{{ controlcenter_version }}"
    restart: always
    ports:
      - "127.0.0.1:8000:80"
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - /home/stereum/.ssh:/root/.ssh
      - /etc/stereum/:/etc/stereum
      - $PWD/inventory.yaml:/opt/app/inventory.yaml
      - $PWD/stereum:/opt/app/stereum-release
    extra_hosts:
      - "{{ docker_host_internal }}:host-gateway"
    networks:
      stereum-admin:
      default:

networks:
  stereum-admin:
    internal: true
  default:
# EOF
